<?php
/**
 * Created by PhpStorm.
 * User: borsosalbert
 * Date: 2014.06.27.
 * Time: 8:56
 */

namespace albertborsos\yii2lib\web;


use Yii;

class Session extends \yii\web\Session{
    public function open()
    {
        if ($this->getIsActive()) {
            return;
        }

        $this->registerSessionHandler();

        $this->setCookieParamsInternal();

        @session_start();

        if ($this->getIsActive()) {
            Yii::info('Session started', __METHOD__);
        } else {
            $error = error_get_last();
            $message = isset($error['message']) ? $error['message'] : 'Failed to start session.';
            Yii::error($message, __METHOD__);
        }
    }

    public function getFlash($key, $defaultValue = null, $delete = false)
    {
        $this->updateFlashCounters();
        return parent::getFlash($key, $defaultValue, $delete); // TODO: Change the autogenerated stub
    }

    public function getAllFlashes($delete = false)
    {
        $this->updateFlashCounters();
        return parent::getAllFlashes($delete); // TODO: Change the autogenerated stub
    }


} 